### ISSUE TITLE
UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by johnfelipe** [RaguramRamamoorthy/coviddetector#1]
File "/home/felipe/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
File "/home/felipe/coviddetector/coviddetectapp.py", line 3, in <module>
    from imageclassification import predict_image_class
File "/home/felipe/coviddetector/imageclassification.py", line 9, in <module>
    resnet18.load_state_dict(torch.load('covid_classifier.pt'))
File "/home/felipe/.local/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "/home/felipe/.local/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)

**Comment by johnfelipe** [comment]
(env) root@eh682214710:~/coviddetector# streamlit run coviddetectapp.py
	2022-01-10 23:55:25.370 Trying to detect encoding from a tiny portion of (13) byte(s).
	2022-01-10 23:55:25.370 ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
	2022-01-10 23:55:25.371 ascii is most likely the one. Stopping the process.

	  You can now view your Streamlit app in your browser.

	  Network URL: http://10.1.0.4:8501
	  External URL: http://20.122.93.89:8501

	Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
	100.0%
	2022-01-10 23:55:27.451 Traceback (most recent call last):
	  File "/root/coviddetector/env/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
		exec(code, module.__dict__)
	  File "/root/coviddetector/coviddetectapp.py", line 3, in <module>
		from imageclassification import predict_image_class
	  File "/root/coviddetector/imageclassification.py", line 9, in <module>
		resnet18.load_state_dict(torch.load('covid_classifier.pt'))
	  File "/root/coviddetector/env/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
		return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
	  File "/root/coviddetector/env/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
		magic_number = pickle_module.load(f, **pickle_load_args)
	_pickle.UnpicklingError: invalid load key, 'v'.

	2022-01-10 23:55:28.018 Traceback (most recent call last):
	  File "/root/coviddetector/env/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
		exec(code, module.__dict__)
	  File "/root/coviddetector/coviddetectapp.py", line 3, in <module>
		from imageclassification import predict_image_class
	  File "/root/coviddetector/imageclassification.py", line 9, in <module>
		resnet18.load_state_dict(torch.load('covid_classifier.pt'))
	  File "/root/coviddetector/env/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
		return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
	  File "/root/coviddetector/env/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
		magic_number = pickle_module.load(f, **pickle_load_args)
	_pickle.UnpicklingError: invalid load key, 'v'.

	2022-01-10 23:55:37.191 Traceback (most recent call last):
	  File "/root/coviddetector/env/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
		exec(code, module.__dict__)
	  File "/root/coviddetector/coviddetectapp.py", line 3, in <module>
		from imageclassification import predict_image_class
	  File "/root/coviddetector/imageclassification.py", line 9, in <module>
		resnet18.load_state_dict(torch.load('covid_classifier.pt'))
	  File "/root/coviddetector/env/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
		return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
	  File "/root/coviddetector/env/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
		magic_number = pickle_module.load(f, **pickle_load_args)
	_pickle.UnpicklingError: invalid load key, 'v'.

how solve this?
